
# You can generate the keys by running the following and then copying the keys into here
#  `wg genkey | tee privatekey | wg pubkey > publickey`

[Interface]
Address = 10.20.0.2/24
PrivateKey =

[Peer]
PublicKey =
Endpoint = your.dns.server:51820
AllowedIPs = 10.20.0.0/24
PersistentKeepalive = 15
